Bookers/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'home/index'
  get 'bookers/show'
  get 'bookers/index'
  get 'bookers/new'
  get 'bookers/:id/edit'=> 'bookers#edit', as: 'edit_bookers'
  get 'bookerss/:id' => 'bookerss#show', as: 'bookers'
  post 'bookers' => 'bookers#create'
  patch 'bookers/:id' => 'bookers#update', as: 'update_bookers'
  delete 'bookers/:id' => 'bookers#destroy', as: 'destroy_bookers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers/app/models/booker.rb
class Booker < ApplicationRecord
end

Bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Bookers/app/controllers/bookers_controller.rb
class BookersController < ApplicationController
  def show
  	@bookers = Bookers.find(params[:id])
  end

  def index
  	@bookerss = Bookers.all
  end

  def new
  	@bookerss = Bookers.new
  end

  def edit
        @post = Bookers.find(params[:id])
  end

  def create
         bookers = Bookers.new(post_params)
         bookers.save
         redirect_to bookers_path(bookers.id)
  end

  def update
        bookers = Bookers.find(params[:id])
        bookers.update(bookers_params)
        redirect_to bookers_path(bookers.id)
  end

   def destroy
        bookers = Bookers.find(params[:id])
        bookers.destroy
        redirect_to bookers_path
   end

   def back
  	@bookers = Bookers.find(params[:id])
   end

     private

    def bookers_params
        params.require(:post).permit(:title, :body)
    end
end

Bookers/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

Bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers/app/helpers/bookers_helper.rb
module BookersHelper
end

Bookers/app/helpers/home_helper.rb
module HomeHelper
end

Bookers/app/views/bookers/edit.html.erb
<h>Editing Book</h1>
<%= form_for(@post) do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Body</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Update Book' %>
    
    <%= link_to "Show", show_bookers_path(@bookers.id) %>
    <%= link_to "Back", index_bookers_path(@books.id) %>
<% end %>

Bookers/app/views/bookers/index.html.erb
<h1>Books</h1>
 <% @bookers.each do |post| %>
 <%= link_to "Show", show_bookers_path(@bookers.id) %>
 <%= link_to "Edit", edit_bookers_path(@books.id) %>
 <%= link_to "Destroy", destroy_bookers_path(@bookers.id), method: :delete, "data-confirm" => "Are you sure？" %>
 <h2>New book</h2>
    <p>Title</p>
     <p>Body</p>
    <span><%=link_to bookers.title, "/bookers/#{bookers.id}" %></span>

 <% end %>

Bookers/app/views/bookers/new.html.erb
<h1>New book</h1>

<%= form_for(@bookers) do |f| %>

<h4>Title</h4>
    <%= f.text_field :title %>

     <h4>Body</h4>
    <%= f.text_area :body %>
 
    <%= f.submit 'Create Book' %>

Bookers/app/views/bookers/show.html.erb
<h2>Book was successfully created.</h2>
<h2>Title</h2>
<p><%= bookers.title %></p>
<h2>Body</h2>
<p><%= @bookers.body %></p>

<%= link_to "Edit", edit_bookers_path(@books.id) %>
<%= link_to "Back", index_bookers_path(@books.id) %>

Bookers/app/views/home/index.html.erb
<html>
  <head>
  <body>
    <h1>ようこそ <strong>Bookers</strong>  へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することができます</p>
<p><a href="/books">start</a></p>
  </body>
  </head>
</html>

Bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>